version: "3"

services:
  rails-api:
    container_name: rails-api
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${API_CONTAINER_PORT}"
    env_file:
      - .${RAILS_ENV}.env
    volumes:
      - .:/rails-api
    ports:
      - "${API_HOST_PORT}:${API_CONTAINER_PORT}"
    depends_on:
      - db
    tty: true
    stdin_open: true
    restart: always # コンテナが停止すると常に再起動

  db:
    container_name: db
    image: postgres:14.7-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    env_file:
      - .${RAILS_ENV}.env
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    restart: always # コンテナが停止すると常に再起動

  reverse-proxy:
    image: nginx:1.25.2-alpine
    volumes:
      - ./reverse-proxy:/etc/nginx
    ports:
      - ${REVERSE_PROXY_HOST_PORT}:${REVERSE_PROXY_CONTAINER_PORT}
    env_file:
      - .${RAILS_ENV}.env

volumes:
  postgres_volume:
