version: "3"

services:
  rails-api:
    container_name: rails-api
    build: .
    command: bundle exec rails s -p ${API_HOST_PORT} -b '${API_CONTAINER_HOST}'
    environment:
      RAILS_ENV: ${RAILS_ENV}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/rails-api
    ports:
      - "${API_HOST}:${API_HOST_PORT}:${API_CONTAINER_PORT}"
    depends_on:
      - db
    tty: true
    stdin_open: true
    restart: always # コンテナが停止すると常に再起動

  db:
    container_name: db
    image: postgres:14.7-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    restart: always # コンテナが停止すると常に再起動

volumes:
  postgres_volume:
