version: "3"

services:
  rails-api:
    container_name: rails-api
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${API_CONTAINER_PORT} -b '0.0.0.0'"
    env_file:
      - .${RAILS_ENV}.env
    volumes:
      - .:/rails-api
    networks:
      - whale-network
    ports:
      - "${API_HOST_PORT}:${API_CONTAINER_PORT}"
    depends_on:
      - db
    tty: true
    stdin_open: true
    extra_hosts:
      - "${PROXY_HOST}:host-gateway"

  db:
    container_name: db
    image: postgres:14.7-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    env_file:
      - .${RAILS_ENV}.env
    networks:
      - whale-network
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    extra_hosts:
      - "${PROXY_HOST}:host-gateway"

  reverse-proxy:
    image: nginx:1.25.2-alpine
    volumes:
      - ./reverse-proxy:/etc/nginx
    ports:
      - ${REVERSE_PROXY_HOST_PORT}:${REVERSE_PROXY_CONTAINER_PORT}
    env_file:
      - .${RAILS_ENV}.env
    extra_hosts:
      - "${PROXY_HOST}:host-gateway"
    networks:
      - whale-network

volumes:
  postgres_volume:

networks:
  whale-network:
