version: "3"

services:
  rails-api:
    container_name: rails-api
    build:
      context: .
      dockerfile: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${API_CONTAINER_PORT} -b '0.0.0.0'"
    env_file:
      - .${RAILS_ENV}.env
    volumes:
      - .:/rails-api
    networks:
      whale-network:
        ipv4_address: ${API_CONTAINER_HOST}
    expose:
      - "${API_CONTAINER_PORT}"
    depends_on:
      - db
    tty: true
    stdin_open: true
    extra_hosts:
      - "${PROXY_HOST}:host-gateway"

  reverse-proxy:
    image: nginx:1.25.2-alpine
    volumes:
      - ./reverse-proxy:/etc/nginx
    ports:
      - ${REVERSE_PROXY_HTTPS_HOST_PORT}:${REVERSE_PROXY_HTTPS_CONTAINER_PORT}
    env_file:
      - .${RAILS_ENV}.env
    extra_hosts:
      - "${PROXY_HOST}:host-gateway"
    networks:
      - whale-network
    depends_on:
      - rails-api

networks:
  whale-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${CONTAINER_NETWORK_SUBNET}
