json.id information_content.id
json.content information_content.content
json.link information_content.link
json.display_link information_content.display_link
json.start_at information_content.start_at
json.end_at information_content.end_at
